// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_tutoring_app/test/presentation/providers/message_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_tutoring_app/data/models/message_model.dart' as _i7;
import 'package:flutter_tutoring_app/data/repositories/message_repository_impl.dart'
    as _i3;
import 'package:flutter_tutoring_app/domain/repositories/irepository.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MessageRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageRepositoryImpl extends _i1.Mock
    implements _i3.MessageRepositoryImpl {
  MockMessageRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get repositoryName => (super.noSuchMethod(
        Invocation.getter(#repositoryName),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#repositoryName),
        ),
      ) as String);

  @override
  _i5.Future<
      _i2.Either<_i6.Failure, List<_i7.MessageModel>>> getConversationMessages(
    String? conversationId, {
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConversationMessages,
          [conversationId],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, List<_i7.MessageModel>>>.value(
                _FakeEither_0<_i6.Failure, List<_i7.MessageModel>>(
          this,
          Invocation.method(
            #getConversationMessages,
            [conversationId],
            {
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, List<_i7.MessageModel>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<Map<String, dynamic>>>>
      getUserConversations(
    String? userId, {
    int? limit = 50,
    int? offset = 0,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getUserConversations,
              [userId],
              {
                #limit: limit,
                #offset: offset,
              },
            ),
            returnValue: _i5.Future<
                    _i2.Either<_i6.Failure, List<Map<String, dynamic>>>>.value(
                _FakeEither_0<_i6.Failure, List<Map<String, dynamic>>>(
              this,
              Invocation.method(
                #getUserConversations,
                [userId],
                {
                  #limit: limit,
                  #offset: offset,
                },
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, List<Map<String, dynamic>>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.MessageModel>> sendMessage({
    required String? conversationId,
    required String? senderId,
    required String? text,
    String? attachmentUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [],
          {
            #conversationId: conversationId,
            #senderId: senderId,
            #text: text,
            #attachmentUrl: attachmentUrl,
          },
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, _i7.MessageModel>>.value(
                _FakeEither_0<_i6.Failure, _i7.MessageModel>(
          this,
          Invocation.method(
            #sendMessage,
            [],
            {
              #conversationId: conversationId,
              #senderId: senderId,
              #text: text,
              #attachmentUrl: attachmentUrl,
            },
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i7.MessageModel>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> markAsRead(String? messageId) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsRead,
          [messageId],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #markAsRead,
            [messageId],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, int>> getUnreadCount(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnreadCount,
          [userId],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, int>>.value(
            _FakeEither_0<_i6.Failure, int>(
          this,
          Invocation.method(
            #getUnreadCount,
            [userId],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, int>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.MessageModel>>> searchMessages(
    String? conversationId,
    String? query,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMessages,
          [
            conversationId,
            query,
          ],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, List<_i7.MessageModel>>>.value(
                _FakeEither_0<_i6.Failure, List<_i7.MessageModel>>(
          this,
          Invocation.method(
            #searchMessages,
            [
              conversationId,
              query,
            ],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, List<_i7.MessageModel>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i6.SyncResult<_i7.MessageModel>>>
      syncData() => (super.noSuchMethod(
            Invocation.method(
              #syncData,
              [],
            ),
            returnValue: _i5.Future<
                    _i2.Either<_i6.Failure,
                        _i6.SyncResult<_i7.MessageModel>>>.value(
                _FakeEither_0<_i6.Failure, _i6.SyncResult<_i7.MessageModel>>(
              this,
              Invocation.method(
                #syncData,
                [],
              ),
            )),
          ) as _i5.Future<
              _i2.Either<_i6.Failure, _i6.SyncResult<_i7.MessageModel>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.MessageModel>>>
      getOfflineData() => (super.noSuchMethod(
            Invocation.method(
              #getOfflineData,
              [],
            ),
            returnValue: _i5
                .Future<_i2.Either<_i6.Failure, List<_i7.MessageModel>>>.value(
                _FakeEither_0<_i6.Failure, List<_i7.MessageModel>>(
              this,
              Invocation.method(
                #getOfflineData,
                [],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, List<_i7.MessageModel>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> saveOfflineData(
          List<_i7.MessageModel>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveOfflineData,
          [data],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #saveOfflineData,
            [data],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, bool>> isDataSynced() =>
      (super.noSuchMethod(
        Invocation.method(
          #isDataSynced,
          [],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, bool>>.value(
            _FakeEither_0<_i6.Failure, bool>(
          this,
          Invocation.method(
            #isDataSynced,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, bool>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.MessageModel>> getById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, _i7.MessageModel>>.value(
                _FakeEither_0<_i6.Failure, _i7.MessageModel>(
          this,
          Invocation.method(
            #getById,
            [id],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i7.MessageModel>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.MessageModel>> create(
          _i7.MessageModel? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [entity],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, _i7.MessageModel>>.value(
                _FakeEither_0<_i6.Failure, _i7.MessageModel>(
          this,
          Invocation.method(
            #create,
            [entity],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i7.MessageModel>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.MessageModel>> update(
    String? id,
    _i7.MessageModel? entity,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            id,
            entity,
          ],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, _i7.MessageModel>>.value(
                _FakeEither_0<_i6.Failure, _i7.MessageModel>(
          this,
          Invocation.method(
            #update,
            [
              id,
              entity,
            ],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i7.MessageModel>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, bool>> delete(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, bool>>.value(
            _FakeEither_0<_i6.Failure, bool>(
          this,
          Invocation.method(
            #delete,
            [id],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, bool>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.MessageModel>>> getAll({
    int? page,
    int? limit,
    Map<String, dynamic>? filters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
          {
            #page: page,
            #limit: limit,
            #filters: filters,
          },
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, List<_i7.MessageModel>>>.value(
                _FakeEither_0<_i6.Failure, List<_i7.MessageModel>>(
          this,
          Invocation.method(
            #getAll,
            [],
            {
              #page: page,
              #limit: limit,
              #filters: filters,
            },
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, List<_i7.MessageModel>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.MessageModel>>> search(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [query],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, List<_i7.MessageModel>>>.value(
                _FakeEither_0<_i6.Failure, List<_i7.MessageModel>>(
          this,
          Invocation.method(
            #search,
            [query],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, List<_i7.MessageModel>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, bool>> exists(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #exists,
          [id],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, bool>>.value(
            _FakeEither_0<_i6.Failure, bool>(
          this,
          Invocation.method(
            #exists,
            [id],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, bool>>);
}
