name: Flutter CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.3'
        channel: 'stable'
    
    - name: Cache Flutter dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.flutter/cache
          ~/.pub-cache
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock' }}
        restore-keys: |
          ${{ runner.os }}-flutter-
    
    - name: Get dependencies
      run: cd app && flutter pub get
    
    - name: Analyze code
      run: cd app && flutter analyze
    
    - name: Run tests
      run: cd app && flutter test --coverage
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: app/coverage/lcov.info
    
    - name: Build APK
      run: cd app && flutter build apk --debug
    
    - name: Build IPA (for MacOS)
      if: matrix.os == 'macos-latest'
      run: cd app && flutter build ios --no-codesign