name: Android CI Build

on:
  push:
    branches:
      - main # or master, or whatever branch you want to build from
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # 1. Checkout the repository code
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2 # 2. Use a dedicated action to set up Flutter
        with:
          channel: 'stable'
          
      - name: 4. Get Dependencies & Clean Build
        run: |
          flutter pub get
          flutter clean # Essential to remove old build artifacts and prevent exit code 1 errors
        working-directory: app/ # <--- CHANGED: Set to 'app/' based on your project structure

      - name: 5. Run Linter and Analyze
        run: flutter analyze
        working-directory: app/ # <--- CHANGED: Set to 'app/' based on your project structure

      - name: 6. Build Android APK (Debug for testing)
        # Change to `flutter build apk --release` if you have signing secrets set up
        run: flutter build apk --debug
        working-directory: app/ # <--- CHANGED: Set to 'app/' based on your project structure
        
      - name: 7. Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
